### ISSUE TITLE
Add service monitor honorLabels to configmap.yaml

### ISSUE THREAD

**Issue by timothymeyers** [marlinspike/dsopbuilder#17]
Add in the workaround for the issue described [here ](https://repo1.dso.mil/platform-one/big-bang/apps/core/monitoring/-/issues/66)

```
monitoring:
  enabled: true
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
    kubeStateMetrics:
        serviceMonitor:
          honorLabels: true
```
